<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_EditEmail</name>
   <tag></tag>
   <elementGuidId>b1791204-98a1-40e9-bbc3-52330d7a78c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[contains(@id,'CustomerEmailTable')]/tbody/tr[last()]/td[last()]/descendant::a[contains(@id,'editEmail')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
