<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_ExpandHold</name>
   <tag></tag>
   <elementGuidId>22d1f18f-7cfe-4016-bb8f-8cdddcc791a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@displayblockname=&quot;ACCOUNT_BALANCE_SUMMARY&quot;]//div[contains(@id,'_wthold_arrow')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
