<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Hold_Clearing</name>
   <tag></tag>
   <elementGuidId>841dacaf-4393-4dc9-9c0d-d1eb7bae1bd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@displayblockname=&quot;ACCOUNT_BALANCE_SUMMARY&quot;]//span[contains(@id,'_wtClearingExpr')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
