<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Hold_Admin</name>
   <tag></tag>
   <elementGuidId>f3643403-d8e2-49f8-ae36-4192a6d5488a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@displayblockname=&quot;ACCOUNT_BALANCE_SUMMARY&quot;]//span[contains(@id,'_wtHoldsAdminExpr')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
