<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Hold_Reserve</name>
   <tag></tag>
   <elementGuidId>6474b904-8d9a-4e85-86ab-3d0396cbdd0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@displayblockname=&quot;ACCOUNT_BALANCE_SUMMARY&quot;]//span[contains(@id,'_wtReserveExpr')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
