<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Hold_PreAuth</name>
   <tag></tag>
   <elementGuidId>c9c9ec53-a140-4460-be34-87a290ed896d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@displayblockname=&quot;ACCOUNT_BALANCE_SUMMARY&quot;]//span[contains(@id,'_wtPreAuthExpr')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
