<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ValidFromDate</name>
   <tag></tag>
   <elementGuidId>bd60876f-0b94-48c8-83f5-39db8f103f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'ValidFromDateInput')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//input[contains(@id,'ValidFromDateInput')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
