<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_LedgerBalanceBefore</name>
   <tag></tag>
   <elementGuidId>48160a8c-215a-4541-9967-1b0ea1236dff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@taskblockname='PostTransaction']//span[contains(@id,'_wtLedgerBalBeforeExpr')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
