<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_AvailableBalanceBefore</name>
   <tag></tag>
   <elementGuidId>a0b48aa1-d6cc-42cf-81b3-38f11d8677c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@taskblockname='PostTransaction']//span[contains(@id,'_wtAvailableBalBeforeExpr')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
