<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_Order</name>
   <tag></tag>
   <elementGuidId>bb3d2927-e31a-486f-813b-7c7e3080ea09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[contains(@id,'OrdersTable')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
