<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Timezone</name>
   <tag></tag>
   <elementGuidId>4d9fcd4c-d7d0-4ce1-bfc3-8dc05bf5345b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'_wtTimeZone')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nGageBanking_Theme_wt20$block$wtHeadingContent$nGageBanking_Account_Tasks_wt7$block$WebPatterns_wt160$block$wtPanelContent$wtTimeZone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nGageBanking_Theme_wt20_block_wtHeadingContent_nGageBanking_Account_Tasks_wt7_block_WebPatterns_wt160_block_wtPanelContent_wtTimeZone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>38</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_Width3 ThemeGrid_MarginGutter Mandatory</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>return OsEnterKey('nGageBanking_Theme_wt20_block_wtHeadingContent_nGageBanking_Account_Tasks_wt7_block_WebPatterns_wt160_block_wtPanelContent_wtOkButton', arguments[0] || window.event);</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	Europe/Andorra
	Europe/Andorra
	Asia/Dubai
	Asia/Kabul
	America/Antigua
	Europe/Tirane
	Asia/Yerevan
	America/Curacao
	Africa/Luanda
	Antarctica/South_Pole
	Antarctica/Casey
	Antarctica/Davis
	Antarctica/DumontDUrville
	Antarctica/Mawson
	Antarctica/McMurdo
	Antarctica/Palmer
	Antarctica/Rothera
	Antarctica/Syowa
	Antarctica/Troll
	Antarctica/Vostok
	America/Buenos_Aires
	America/Cordoba
	America/Catamarca
	America/Argentina/La_Rioja
	America/Jujuy
	America/Argentina/San_Luis
	America/Mendoza
	America/Argentina/Rio_Gallegos
	America/Argentina/Salta
	America/Argentina/Tucuman
	America/Argentina/San_Juan
	America/Argentina/Ushuaia
	Pacific/Pago_Pago
	Europe/Vienna
	Australia/Adelaide
	Australia/Broken_Hill
	Australia/Brisbane
	Australia/Darwin
	Australia/Eucla
	Australia/Hobart
	Australia/Currie
	Australia/Lindeman
	Australia/Lord_Howe
	Australia/Melbourne
	Antarctica/Macquarie
	Australia/Perth
	Australia/Sydney
	America/Aruba
	Asia/Baku
	Europe/Sarajevo
	America/Barbados
	Asia/Dhaka
	Europe/Brussels
	Africa/Ouagadougou
	Europe/Sofia
	Asia/Bahrain
	Africa/Bujumbura
	Africa/Porto-Novo
	Atlantic/Bermuda
	Asia/Brunei
	America/La_Paz
	America/Kralendijk
	America/Araguaina
	America/Belem
	America/Boa_Vista
	America/Cuiaba
	America/Campo_Grande
	America/Eirunepe
	America/Noronha
	America/Fortaleza
	America/Manaus
	America/Maceio
	America/Porto_Velho
	America/Rio_Branco
	America/Recife
	America/Sao_Paulo
	America/Bahia
	America/Santarem
	America/Nassau
	Asia/Thimphu
	Africa/Gaborone
	Europe/Minsk
	America/Belize
	America/Creston
	America/Edmonton
	America/Rainy_River
	America/Fort_Nelson
	America/Glace_Bay
	America/Goose_Bay
	America/Halifax
	America/Iqaluit
	America/Moncton
	America/Montreal
	America/Nipigon
	America/Pangnirtung
	America/Resolute
	America/Regina
	America/St_Johns
	America/Thunder_Bay
	America/Toronto
	America/Vancouver
	America/Winnipeg
	America/Blanc-Sablon
	America/Cambridge_Bay
	America/Dawson
	America/Dawson_Creek
	America/Rankin_Inlet
	America/Inuvik
	America/Whitehorse
	America/Swift_Current
	America/Yellowknife
	America/Coral_Harbour
	Indian/Cocos
	Africa/Lubumbashi
	Africa/Kinshasa
	Africa/Bangui
	Africa/Brazzaville
	Europe/Zurich
	Africa/Abidjan
	Pacific/Rarotonga
	Pacific/Easter
	America/Punta_Arenas
	America/Santiago
	Africa/Douala
	Asia/Shanghai
	Asia/Urumqi
	America/Bogota
	America/Costa_Rica
	CST6CDT
	America/Havana
	Atlantic/Cape_Verde
	Indian/Christmas
	Asia/Famagusta
	Asia/Nicosia
	Europe/Prague
	Europe/Berlin
	Europe/Busingen
	Africa/Djibouti
	Europe/Copenhagen
	America/Dominica
	America/Santo_Domingo
	Pacific/Galapagos
	America/Guayaquil
	Europe/Tallinn
	Africa/Cairo
	Africa/El_Aaiun
	Africa/Asmera
	Africa/Ceuta
	Atlantic/Canary
	Europe/Madrid
	EST5EDT
	Africa/Addis_Ababa
	Europe/Helsinki
	Europe/Mariehamn
	Pacific/Fiji
	Atlantic/Stanley
	Pacific/Kosrae
	Pacific/Ponape
	Pacific/Truk
	Atlantic/Faeroe
	Europe/Paris
	Africa/Libreville
	Asia/Gaza
	Europe/London
	America/Grenada
	Asia/Tbilisi
	America/Cayenne
	Europe/Guernsey
	Africa/Accra
	Europe/Gibraltar
	America/Danmarkshavn
	America/Godthab
	America/Scoresbysund
	America/Thule
	Africa/Banjul
	Etc/GMT
	Africa/Conakry
	America/Guadeloupe
	America/Marigot
	America/St_Barthelemy
	Africa/Malabo
	Europe/Athens
	Atlantic/South_Georgia
	America/Guatemala
	Pacific/Guam
	Africa/Bissau
	America/Guyana
	Asia/Hebron
	Asia/Hong_Kong
	Indian/Comoro
	America/Tegucigalpa
	Europe/Zagreb
	America/Port-au-Prince
	Europe/Budapest
	America/Cayman
	Asia/Jayapura
	Asia/Jakarta
	Asia/Makassar
	Asia/Pontianak
	Europe/Dublin
	Europe/Isle_of_Man
	Asia/Calcutta
	Indian/Chagos
	Asia/Baghdad
	Asia/Tehran
	Atlantic/Reykjavik
	Europe/Rome
	Asia/Jerusalem
	Europe/Jersey
	America/Jamaica
	Asia/Amman
	Asia/Tokyo
	Africa/Nairobi
	Asia/Bishkek
	Asia/Phnom_Penh
	Pacific/Kiritimati
	Pacific/Enderbury
	Pacific/Tarawa
	America/St_Kitts
	Asia/Pyongyang
	Asia/Seoul
	Asia/Kuwait
	Asia/Aqtau
	Asia/Aqtobe
	Asia/Almaty
	Asia/Atyrau
	Asia/Qyzylorda
	Asia/Oral
	Asia/Vientiane
	Asia/Beirut
	America/St_Lucia
	Europe/Vaduz
	Asia/Colombo
	Africa/Monrovia
	Africa/Maseru
	Europe/Vilnius
	Europe/Luxembourg
	Europe/Riga
	Africa/Tripoli
	Africa/Casablanca
	Europe/Monaco
	Europe/Chisinau
	Europe/Podgorica
	Indian/Antananarivo
	Pacific/Kwajalein
	Pacific/Majuro
	Europe/Skopje
	Africa/Bamako
	Asia/Rangoon
	Asia/Choibalsan
	Asia/Hovd
	Asia/Ulaanbaatar
	Asia/Macau
	Pacific/Saipan
	America/Martinique
	Africa/Nouakchott
	America/Montserrat
	MST7MDT
	Europe/Malta
	Indian/Mauritius
	Indian/Maldives
	Africa/Blantyre
	America/Chihuahua
	America/Cancun
	America/Hermosillo
	America/Matamoros
	America/Mexico_City
	America/Merida
	America/Monterrey
	America/Mazatlan
	America/Ojinaga
	America/Bahia_Banderas
	America/Santa_Isabel
	America/Tijuana
	Asia/Kuching
	Asia/Kuala_Lumpur
	Africa/Maputo
	Africa/Windhoek
	Pacific/Noumea
	Africa/Niamey
	Pacific/Norfolk
	Africa/Lagos
	America/Managua
	Europe/Amsterdam
	Europe/Oslo
	Asia/Katmandu
	Pacific/Nauru
	Pacific/Niue
	Pacific/Auckland
	Pacific/Chatham
	Asia/Muscat
	America/Panama
	PST8PDT
	America/Lima
	Pacific/Gambier
	Pacific/Marquesas
	Pacific/Tahiti
	Pacific/Port_Moresby
	Pacific/Bougainville
	Asia/Manila
	Asia/Karachi
	Europe/Warsaw
	America/Miquelon
	Pacific/Pitcairn
	America/Puerto_Rico
	Atlantic/Azores
	Pacific/Palau
	America/Asuncion
	Asia/Qatar
	Indian/Reunion
	Europe/Bucharest
	Europe/Belgrade
	Europe/Astrakhan
	Asia/Barnaul
	Asia/Chita
	Asia/Anadyr
	Asia/Magadan
	Asia/Irkutsk
	Europe/Kaliningrad
	Asia/Khandyga
	Asia/Krasnoyarsk
	Europe/Samara
	Europe/Kirov
	Europe/Moscow
	Asia/Novokuznetsk
	Asia/Omsk
	Asia/Novosibirsk
	Asia/Kamchatka
	Europe/Saratov
	Asia/Srednekolymsk
	Asia/Tomsk
	Europe/Ulyanovsk
	Asia/Ust-Nera
	Asia/Sakhalin
	Europe/Volgograd
	Asia/Vladivostok
	Asia/Yekaterinburg
	Asia/Yakutsk
	Africa/Kigali
	Asia/Riyadh
	Pacific/Guadalcanal
	Indian/Mahe
	Africa/Khartoum
	Europe/Stockholm
	Asia/Singapore
	Atlantic/St_Helena
	Europe/Ljubljana
	Arctic/Longyearbyen
	Europe/Bratislava
	Africa/Freetown
	Europe/San_Marino
	Africa/Dakar
	Africa/Mogadishu
	America/Paramaribo
	Africa/Juba
	Africa/Sao_Tome
	America/El_Salvador
	America/Lower_Princes
	Asia/Damascus
	Africa/Mbabane
	America/Grand_Turk
	Africa/Ndjamena
	Indian/Kerguelen
	Africa/Lome
	Asia/Bangkok
	Asia/Dushanbe
	Pacific/Fakaofo
	Asia/Dili
	Asia/Ashgabat
	Africa/Tunis
	Pacific/Tongatapu
	Europe/Istanbul
	America/Port_of_Spain
	Pacific/Funafuti
	Asia/Taipei
	Africa/Dar_es_Salaam
	Europe/Kiev
	Europe/Zaporozhye
	Europe/Simferopol
	Europe/Uzhgorod
	Africa/Kampala
	Pacific/Wake
	Pacific/Johnston
	Pacific/Midway
	America/Adak
	America/Indiana/Marengo
	America/Anchorage
	America/Boise
	America/Chicago
	America/Denver
	America/Detroit
	Pacific/Honolulu
	America/Indianapolis
	America/Indiana/Vevay
	America/Juneau
	America/Indiana/Knox
	America/Los_Angeles
	America/Louisville
	America/Menominee
	America/Kentucky/Monticello
	America/Metlakatla
	America/North_Dakota/Center
	America/North_Dakota/New_Salem
	America/New_York
	America/Indiana/Vincennes
	America/Nome
	America/Phoenix
	America/Sitka
	America/Indiana/Tell_City
	America/Indiana/Winamac
	America/Indiana/Petersburg
	America/North_Dakota/Beulah
	America/Yakutat
	UTC
	Etc/GMT-1
	Etc/GMT-2
	Etc/GMT-3
	Etc/GMT-4
	Etc/GMT-5
	Etc/GMT-6
	Etc/GMT-7
	Etc/GMT-8
	Etc/GMT-9
	Etc/GMT-10
	Etc/GMT-11
	Etc/GMT-12
	Etc/GMT-13
	Etc/GMT-14
	Etc/GMT+1
	Etc/GMT+2
	Etc/GMT+3
	Etc/GMT+4
	Etc/GMT+5
	Etc/GMT+6
	Etc/GMT+7
	Etc/GMT+8
	Etc/GMT+9
	Etc/GMT+10
	Etc/GMT+11
	Etc/GMT+12
	America/Montevideo
	Asia/Samarkand
	Asia/Tashkent
	Europe/Vatican
	America/St_Vincent
	America/Caracas
	America/Tortola
	America/St_Thomas
	Asia/Saigon
	Pacific/Efate
	Pacific/Wallis
	Pacific/Apia
	Asia/Aden
	Indian/Mayotte
	Africa/Johannesburg
	Africa/Lusaka
	Africa/Harare

</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nGageBanking_Theme_wt20_block_wtHeadingContent_nGageBanking_Account_Tasks_wt7_block_WebPatterns_wt160_block_wtPanelContent_wtTimeZone&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='nGageBanking_Theme_wt20_block_wtHeadingContent_nGageBanking_Account_Tasks_wt7_block_WebPatterns_wt160_block_wtPanelContent_wtTimeZone']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nGageBanking_Theme_wt20_block_wtHeadingContent_nGageBanking_Account_Tasks_wt7_block_WebPatterns_wt160_block_wtPanelContent_wtTimeZone_CN']/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Zone'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brokered'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statement Frequency'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paper Statement'])[1]/preceding::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
   </webElementXpaths>
</WebElementEntity>
