<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_EditPhoneNo</name>
   <tag></tag>
   <elementGuidId>05578aec-d29f-47e6-9842-c8b2506b17ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[contains(@id,'_wtCustomerPhoneTable')]/descendant::a[contains(@id,'CustomerPhoneTable')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
