<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_GeneralCaseInfo</name>
   <tag></tag>
   <elementGuidId>b591eff2-4df8-40fd-99ac-1ee75992c228</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='eform_mcb67676_phBO_3_BO_BOstatic_3_BOstatic_2_BOstatic_1_BOstatic_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
