<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Table_Holds</name>
   <tag></tag>
   <elementGuidId>0baa341a-9b3a-4ca4-a957-b3fe2541d0bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[contains(@id,'HoldsTable')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
